/**:
  ros__parameters:
    fusion_distance: 100.0
    trust_object_distance: 100.0
    trust_object_iou_mode: "iou"
    non_trust_object_iou_mode: "iou_x"
    use_cluster_semantic_type: false
    only_allow_inside_cluster: true
    roi_scale_factor: 1.1
    iou_threshold: 0.65
    unknown_iou_threshold: 0.1
    remove_unknown: false

    # fusion interface common params
    debug_mode: false
    image_buffer_size: 15
    filter_scope_min_x: -100.0
    filter_scope_min_y: -100.0
    filter_scope_min_z: -100.0
    filter_scope_max_x: 100.0
    filter_scope_max_y: 100.0
    filter_scope_max_z: 100.0
