/**:
  ros__parameters:
    enable_whole_load: true
    enable_downsampled_whole_load: false
    enable_partial_load: true
    enable_differential_load: true

    # only used when downsample_whole_load enabled
    leaf_size: 3.0 # downsample leaf size [m]

    # only used when differential_load enabled
    map_upper_limit: 1717986917 # limit map size [byte]
