/**:
  ros__parameters:
    enable_whole_load: true
    enable_downsampled_whole_load: false
    enable_partial_load: true
    enable_differential_load: true

    # only used when downsample_whole_load enabled
    leaf_size: 3.0 # downsample leaf size [m]

    # only used when differential_load enabled
    # limit data size [byte] of topic/service/action (determined by cyclonedds).
    # Default value is calculated as follows;
    #  map_upper_limit = floor((maximum receive buffer size)* 0.8)
    # If maximum receive buffer size in your PC's environment is 2147483647, map_upper_limit is 1717986917.
    map_upper_limit: 1717986917
